### ISSUE TITLE
Fails make on ubuntu. 

### ISSUE THREAD

**Issue by nicobrinkkemper** [insin/nwb-sass#19]
1. npm install this package on clean ubuntu
result: https://techoverflow.net/2018/06/04/fixing-npm-node-gyp-error-not-found-make-on-ubuntu/
fix: sudo apt install build-essential

2. npm install this package
result: 
```
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
In file included from .../.node-gyp/12.9.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/create_string.cpp:1:
.../.node-gyp/12.9.1/include/node/v8.h:3008:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
.../.node-gyp/12.9.1/include/node/v8.h:3008:5: note:   candidate expects 2 arguments, 1 provided
binding.target.mk:129: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory
```

**Comment by nicobrinkkemper** [comment]
Possible fix: update node-sass to >4.12.0

**Comment by nukeop** [comment]
Also fails on Arch

**Comment by doums** [comment]
Same issue here on Arch too:
`yarn` output:
```
make : on quitte le répertoire « /home/pierre/Documents/owp/aw-common-ui/node_modules/nwb-sass/node_modules/node-sass/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pierre/Documents/owp/aw-common-ui/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.7-arch1-1-ARCH
gyp ERR! command "/opt/node/bin/node" "/home/pierre/Documents/owp/aw-common-ui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/pierre/Documents/owp/aw-common-ui/node_modules/nwb-sass/node_modules/node-sass
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.8.0
```
package.json
```
  ...
  "node-sass-chokidar": "^1.3.5",
},
"devDependencies": {
   ...
  "nwb": "^0.21.5",
  "nwb-sass": "^0.9.0",
  "sass-loader": "^7.0.1"
```
Any solution on this ?
